# data volume
mysqldata:
  image: busybox
  volumes:
   - /var/lib/mysql
# mysql
mysql:
  image: mysql
  volumes:
    - ./mysql_conf.d:/etc/mysql/conf.d
  volumes_from:
    - mysqldata
  expose:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: db_name
# laravel
laravel:
  image: kotamat/laravel
  volumes_from:
    - mysqldata
  links:
    - mysql:mysql_db
  ports:
    - "80:80"
  environment:
    APP: local
  volumes:
    - ../:/app
